setup:
	@echo "Setting up the project using pipenv and requirements.txt..."
	pipenv install
	pipenv install -r requirement.txt
	@echo "Setup complete."

run:
	@echo "Running Backend......"
	python main.py
