setup:
	@echo "Setting up the project using pipenv and requirements.txt..."
	pipenv install
	pipenv shell
	pipenv install -r requirements.txt
	@echo "Setup complete."

run:
	@echo "Running Backend......"
	python main.py
